// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdcniocbahspnefbhlby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkY25pb2NiYWhzcG5lZmJobGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDY5NDMsImV4cCI6MjA2MDkyMjk0M30.uRhMPBds2HnVhYABWnD5casflxuSKv7pa57swVUa_GA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);